
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author laura
 */
public class loginprincipal extends javax.swing.JFrame {

    /**
     * Creates new form loginprincipal
     */
    public loginprincipal() {
        initComponents();
        ImageIcon imagen1 = new ImageIcon(getClass().getResource("/imagenes/car-jump.gif"));
        ImageIcon imagen2 = new ImageIcon(getClass().getResource("/imagenes/amshopby-overlay.gif"));
        ImageIcon imagen3 = new ImageIcon(getClass().getResource("/imagenes/Captura.PNG"));
        Icon fondo1= new ImageIcon(imagen1.getImage().getScaledInstance(lblimagen1.getWidth(), lblimagen1.getHeight(), Image.SCALE_DEFAULT));
        Icon fondo2= new ImageIcon(imagen2.getImage().getScaledInstance(lblimagen2.getWidth(), lblimagen2.getHeight(), Image.SCALE_DEFAULT));
        Icon fondo3= new ImageIcon(imagen3.getImage().getScaledInstance(lblimagen3.getWidth(), lblimagen3.getHeight(), Image.SCALE_DEFAULT));
        
        


        lblimagen1.setIcon(fondo1);
        lblimagen2.setIcon(fondo2);
        lblimagen3.setIcon(fondo3);
        this.repaint();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        textField1 = new java.awt.TextField();
        textField2 = new java.awt.TextField();
        lblimagen2 = new javax.swing.JLabel();
        lblimagen3 = new javax.swing.JLabel();
        lblimagen1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textField1.setFont(new java.awt.Font("Assistant ExtraLight", 0, 18)); // NOI18N
        textField1.setText("textField1");
        jPanel1.add(textField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, 290, 30));

        textField2.setFont(new java.awt.Font("Assistant ExtraLight", 0, 18)); // NOI18N
        textField2.setText("textField1");
        jPanel1.add(textField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 290, 30));

        lblimagen2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(lblimagen2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 61, 58));

        lblimagen3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblimagen3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblimagen3MouseClicked(evt);
            }
        });
        jPanel1.add(lblimagen3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, 470, 240));

        lblimagen1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblimagen1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblimagen1MouseClicked(evt);
            }
        });
        jPanel1.add(lblimagen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 30, 490, 260));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 822, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblimagen1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblimagen1MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_lblimagen1MouseClicked

    private void lblimagen3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblimagen3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblimagen3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginprincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblimagen1;
    private javax.swing.JLabel lblimagen2;
    private javax.swing.JLabel lblimagen3;
    private java.awt.TextField textField1;
    private java.awt.TextField textField2;
    // End of variables declaration//GEN-END:variables
}
